import { AppLayoutWrapper } from '@/components/custom/AppShell/AppLayoutWrapper';
import { ThemeProvider } from '@/components/custom/theme/theme-provider';
import {
	SidebarProvider,
	SidebarTrigger,
} from '@/components/shadcn-ui/sidebar';
import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<ThemeProvider
				attribute='class'
				defaultTheme='system'
				enableSystem
				disableTransitionOnChange
			>
				<body>
					{' '}
					<SidebarProvider>
						<AppLayoutWrapper />
						<main>
							<SidebarTrigger />
							{children}
						</main>
					</SidebarProvider>
				</body>
			</ThemeProvider>
		</html>
	);
}
